#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

GL4ES_ROOT="${GL4ES_ROOT:-/Users/renruisi/Desktop/Code/gl4es}"
GL4ES_LIB="${GL4ES_ROOT}/lib/libGL.a"

if [ ! -f "${GL4ES_LIB}" ]; then
  echo "Missing gl4es static library: ${GL4ES_LIB}" >&2
  exit 1
fi

emcc gl4es_bridge.c \
  -I"${GL4ES_ROOT}/include" \
  "${GL4ES_LIB}" \
  -O2 \
  -sENVIRONMENT=web \
  -sMODULARIZE=1 \
  -sEXPORT_NAME=createV86GL4ES \
  -sALLOW_MEMORY_GROWTH=1 \
  -sFULL_ES2=1 \
  -sMIN_WEBGL_VERSION=1 \
  -sMAX_WEBGL_VERSION=2 \
  -sGL_ENABLE_GET_PROC_ADDRESS=1 \
  -sEXPORTED_RUNTIME_METHODS='["ccall","cwrap","HEAPU8"]' \
  -sEXPORTED_FUNCTIONS='[
    "_malloc",
    "_free",
    "_v86glMakeCurrent",
    "_v86glResize",
    "_v86glReleaseCurrent",
    "_v86glDestroyRenderer",
    "_v86gl_glViewport",
    "_v86gl_glClearColor",
    "_v86gl_glClear",
    "_v86gl_glBegin",
    "_v86gl_glEnd",
    "_v86gl_glColor4f",
    "_v86gl_glVertex3f",
    "_v86gl_glVertex4f",
    "_v86gl_glFlush",
    "_v86gl_glFinish",
    "_v86gl_glMatrixMode",
    "_v86gl_glLoadIdentity",
    "_v86gl_glLoadMatrixf",
    "_v86gl_glMultMatrixf",
    "_v86gl_glFrustum",
    "_v86gl_glOrtho",
    "_v86gl_glTranslatef",
    "_v86gl_glRotatef",
    "_v86gl_glScalef",
    "_v86gl_glPushMatrix",
    "_v86gl_glPopMatrix",
    "_v86gl_glEnable",
    "_v86gl_glDisable",
    "_v86gl_glDepthFunc",
    "_v86gl_glClearDepth",
    "_v86gl_glDepthRange",
    "_v86gl_glClearStencil",
    "_v86gl_glStencilFunc",
    "_v86gl_glStencilMask",
    "_v86gl_glStencilOp",
    "_v86gl_glShadeModel",
    "_v86gl_glCullFace",
    "_v86gl_glFrontFace",
    "_v86gl_glHint",
    "_v86gl_glPushAttrib",
    "_v86gl_glPopAttrib",
    "_v86gl_glPushClientAttrib",
    "_v86gl_glPopClientAttrib",
    "_v86gl_glDrawBuffer",
    "_v86gl_glReadBuffer",
    "_v86gl_glReadPixels",
    "_v86gl_glGenTextures",
    "_v86gl_glDeleteTextures",
    "_v86gl_glBindTexture",
    "_v86gl_glTexImage1D",
    "_v86gl_glTexImage2D",
    "_v86gl_glTexImage3D",
    "_v86gl_glTexSubImage1D",
    "_v86gl_glTexSubImage3D",
    "_v86gl_glCompressedTexImage2D",
    "_v86gl_glCompressedTexImage1D",
    "_v86gl_glCompressedTexImage3D",
    "_v86gl_glCompressedTexSubImage1D",
    "_v86gl_glCompressedTexSubImage2D",
    "_v86gl_glCompressedTexSubImage3D",
    "_v86gl_glTexSubImage2D",
    "_v86gl_glCopyTexImage1D",
    "_v86gl_glCopyTexImage2D",
    "_v86gl_glCopyTexSubImage1D",
    "_v86gl_glCopyTexSubImage2D",
    "_v86gl_glTexParameteri",
    "_v86gl_glTexParameterf",
    "_v86gl_glTexParameteriv4",
    "_v86gl_glTexParameterfv4",
    "_v86gl_glPixelStorei",
    "_v86gl_glTexEnvi",
    "_v86gl_glTexEnvf",
    "_v86gl_glTexEnviv4",
    "_v86gl_glTexEnvfv4",
    "_v86gl_glTexCoord2f",
    "_v86gl_glTexCoord4f",
    "_v86gl_glTexGeni",
    "_v86gl_glTexGenf",
    "_v86gl_glTexGeniv4",
    "_v86gl_glTexGenfv4",
    "_v86gl_glClipPlane4d",
    "_v86gl_glColorMaterial",
    "_v86gl_glActiveTexture",
    "_v86gl_glClientActiveTexture",
    "_v86gl_glMultiTexCoord4f",
    "_v86gl_glNormal3f",
    "_v86gl_glFogf",
    "_v86gl_glFogi",
    "_v86gl_glFogfv4",
    "_v86gl_glMaterialf",
    "_v86gl_glMateriali",
    "_v86gl_glMaterialfv4",
    "_v86gl_glMaterialiv4",
    "_v86gl_glLightf",
    "_v86gl_glLighti",
    "_v86gl_glLightfv4",
    "_v86gl_glLightiv4",
    "_v86gl_glLightModelf",
    "_v86gl_glLightModeli",
    "_v86gl_glLightModelfv4",
    "_v86gl_glLightModeliv4",
    "_v86gl_glBlendFunc",
    "_v86gl_glBlendColor",
    "_v86gl_glBlendEquation",
    "_v86gl_glBlendFuncSeparate",
    "_v86gl_glSampleCoverage",
    "_v86gl_glGenerateMipmap",
    "_v86gl_glFogCoordf",
    "_v86gl_glSecondaryColor3f",
    "_v86gl_glPointParameterf",
    "_v86gl_glPointParameterfv3",
    "_v86gl_glPointParameteri",
    "_v86gl_glPointParameteriv",
    "_v86gl_glWindowPos3f",
    "_v86gl_glRasterPos4f",
    "_v86gl_glPointSize",
    "_v86gl_glLineStipple",
    "_v86gl_glLogicOp",
    "_v86gl_glPixelTransferf",
    "_v86gl_glPixelTransferi",
    "_v86gl_glPixelZoom",
    "_v86gl_glPixelMapfv",
    "_v86gl_glPixelMapuiv",
    "_v86gl_glPixelMapusv",
    "_v86gl_glDrawPixels",
    "_v86gl_glBitmap",
    "_v86gl_glCopyPixels",
    "_v86gl_glClearAccum",
    "_v86gl_glAccum",
    "_v86gl_glPolygonStipple",
    "_v86gl_glAlphaFunc",
    "_v86gl_glDepthMask",
    "_v86gl_glColorMask",
    "_v86gl_glScissor",
    "_v86gl_glLineWidth",
    "_v86gl_glPolygonMode",
    "_v86gl_glPolygonOffset",
    "_v86gl_glEnableClientState",
    "_v86gl_glDisableClientState",
    "_v86gl_glDrawArraysPacked",
    "_v86gl_glDrawElementsPacked",
    "_v86gl_glDrawArraysPackedMT",
    "_v86gl_glDrawElementsPackedMT"
  ]' \
  -o gl4es.js

echo "Generated gl4es.js and gl4es.wasm"
