#!/usr/bin/env python3
"""Generate the diagnostic proxy's compact GL opcode-name table."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "openglproxy" / "opengl32_proxy.c"
OUTPUT = ROOT / "openglproxy" / "gl_opcode_names.h"

source = SOURCE.read_text(encoding="utf-8")
entries = [(int(value), name) for name, value in re.findall(
    r"\bGLFN_([A-Z0-9_]+)\s*=\s*(\d+)\s*,?", source)]
if not entries:
    raise SystemExit("no GLFN opcodes found")

by_value = {}
for value, name in entries:
    previous = by_value.setdefault(value, name)
    if previous != name:
        raise SystemExit(f"duplicate opcode {value}: {previous}, {name}")

count = max(by_value) + 1
lines = [
    "/* Generated by tools/gen_gl_opcode_names.py; do not edit. */",
    "#ifndef V86GL_OPCODE_NAMES_H",
    "#define V86GL_OPCODE_NAMES_H",
    "",
    f"#define V86GL_OPCODE_NAME_COUNT {count}u",
    "static const char *const g_v86gl_opcode_names[V86GL_OPCODE_NAME_COUNT] = {",
    '    [0] = "UNKNOWN",',
]
for value in sorted(by_value):
    lines.append(f'    [{value}] = "{by_value[value]}",')
lines += [
    "};",
    "",
    "static const char *v86gl_opcode_name(unsigned int opcode)",
    "{",
    "    if (opcode >= V86GL_OPCODE_NAME_COUNT ||",
    "            !g_v86gl_opcode_names[opcode])",
    '        return "UNKNOWN";',
    "    return g_v86gl_opcode_names[opcode];",
    "}",
    "",
    "#endif",
    "",
]
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"generated {OUTPUT} ({count - 1} opcodes)")
